const products = [
    {
      image: "./images/Products/1.png",
      name: "Tokyo Sour",
      type: "Ale",
      subtype: "Gose",
      alchohol: 4.3,
      price: 50,
    },
    {
      image: "./images/Products/2.png",
      name: "Centennial IPA",
      type: "Ale",
      subtype: "IPA",
      alchohol: 0,
      price: 35,
    },
    {
      image: "./images/Products/3.png",
      name: "RIBA",
      type: "Lager",
      subtype: "Unfiltered Pils",
      alchohol: 4.5,
      price: 25,
    },
    {
      image: "./images/Products/4.png",
      name: "Lust For Life",
      type: "Ale",
      subtype: "DDH IPA",
      alchohol: 0,
      price: 35,
    },
    {
      image: "./images/Products/5.png",
      name: "7 Hop 7 Grain",
      type: "Ale",
      subtype: "DDH IPA",
      alchohol: 0,
      price: 35,
    },
    {
      image: "./images/Products/6.png",
      name: "Liquid Cocaine",
      type: "Ale",
      subtype: "Double IPA",
      alchohol: 9,
      price: 75,
    },
    {
      image: "./images/Products/7.png",
      name: "IDAHO 7",
      type: "Ale",
      subtype: "IPA",
      alchohol: 0,
      price: 35,
    },
    {
      image: "./images/Products/8.png",
      name: "Tokyo Lemonade",
      type: "Ale",
      subtype: "Gose",
      alchohol: 4.2,
      price: 50,
    },
    {
      image: "./images/Products/9.png",
      name: "Mad House",
      type: "Ale",
      subtype: "DDH IPA",
      alchohol: 5.5,
      price: 75,
    },
    {
      image: "./images/Products/10.png",
      name: "Mango Bay",
      type: "Ale",
      subtype: "Pale Ale",
      alchohol: 5.2,
      price: 65,
    },
    {
      image: "./images/Products/11.png",
      name: "New York Mocaccino",
      type: "Ale",
      subtype: "Milk Stout",
      alchohol: 7,
      price: 75,
    },
    {
      image: "./images/Products/12.png",
      name: "Monkey Temple",
      type: "Lager",
      subtype: "Hefeweizen",
      alchohol: 4.6,
      price: 75,
    },
    {
      image: "./images/Products/13.png",
      name: "Black Boar",
      type: "Ale",
      subtype: "Oatmeal Stout",
      alchohol: 10.2,
      price: 70,
    },
    {
      image: "./images/Products/14.png",
      name: "Black Boar (Bourbon)",
      type: "Ale",
      subtype: "Oatmeal Stout",
      alchohol: 10.2,
      price: 75,
    },
    {
      image: "./images/Products/15.png",
      name: "Popstar",
      type: "Ale",
      subtype: "Gluten Free IPA",
      alchohol: 4.6,
      price: 55,
    },
    {
      image: "./images/Products/16.png",
      name: "STRATA",
      type: "Ale",
      subtype: "IPA",
      alchohol: 0,
      price: 45,
    },
    {
      image: "./images/Products/17.png",
      name: "SABRO GALAXY",
      type: "Ale",
      subtype: "DDH IPA",
      alchohol: 0,
      price: 45,
    },
    {
      image: "./images/Products/18.png",
      name: "SABRO",
      type: "Ale",
      subtype: "IPA",
      alchohol: 0,
      price: 45,
    },
    {
      image: "./images/Products/19.png",
      name: "AZACCA",
      type: "Ale",
      subtype: "IPA",
      alchohol: 0,
      price: 45,
    },
    {
      image: "./images/Products/20.png",
      name: "TROPIC OF NOW",
      type: "Ale",
      subtype: "DDH IPA",
      alchohol: 0,
      price: 45,
    },
  ];